name: Simple Artifact Workflow
on: workflow_dispatch
jobs:
    build-and-upload-artifact:
        runs-on: ubuntu-latest
        steps:
            - name: Create some files
              run: |
                  mkdir my_output
                  echo "This is file content" > myoutput/file1.txt
                  echo "This is file2 content" > my_output/file2.txt
            - name: Upload artifact
              uses: actions/upload-artifact
              with:
                  name: my-generated-files
                  path: my_output/
