name: create-release
on: [push, pull_request]
jobs:
    build-and-test:
        if: false
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - name: Get code
              uses: actions/checkout@v3
            - name: Install dependencies
              run: npm ci
            - name: Test code
              run: npm run test
            - name: Build code
              run: npm run build
            - name: Create Release
              id: create_release
              uses: actions/create-release@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  tag_name: 1.2.3
                  release_name: Release 1.2.3
                  body: |
                      # Release Notes
                      This is a new release!
                  draft: false # Set to true if you want to create a draft release first
                  prerelease: false # Set to true for pre-releases
