name: CodeQL

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
    schedule:
        - cron: "0 0 * * 0" # Weekly scan on Sunday at midnight

jobs:
    analyze:
        name: Analyze
        runs-on: ubuntu-latest
        permissions:
            contents: read
            security-events: write

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Initialize CodeQL
              uses: github/codeql-action/init@v3
              with:
                  languages: javascript, python # Specify the languages in your project

            - name: Autobuild (for compiled languages)
              uses: github/codeql-action/autobuild@v3

            - name: Perform CodeQL Analysis
              uses: github/codeql-action/analyze@v3
