name: Schedule
on:
    schedule:
        - cron: "* 1 * * *"
    workflow_dispatch:
jobs:
    echo_test:
        runs-on: ubuntu-latest
        steps:
            - name: Echo time
              run: echo "Event triggered"
