name: run-scripts
on: workflow_dispatch
jobs:
    run-script-job:
        runs-on: ubuntu-latest
        steps:
            - id: checkout
              uses: actions/checkout@v5
            - id: run-script-step
              run: sh ./scripts/my-script.sh
